dotnet/designs

accepted/file-enumeration.md

This is a proposal to provide a performant extensibility point for file enumeration in System.IO.
This is based on the existing internal Windows implementation, see the CoreFX master branch for some portion of this in action. A branch implemented to spec (for Windows only) can be found here: https://github.com/JeremyKuhne/corefx/tree/findpublic
@terrajobst, @pjanotti, @danmosemsft

Initial draft of file enumeration design doc.

---

README.md
proposed/verifiable-ref-returns.md

A proposal for extension of IL verification rules that would allow byref returns in verifiable code and validate that they are used in type-safe manner.
---
Motivation -
There seems to be enough interest in making typesafe code emitted by current compilers formally verifiable, so we need a central location where we discuss and agree on the rules. 
The other areas that would need to be addressed are: [readonly references](https://github.com/dotnet/designs/pull/21) (type-safe code may not be verifiable according to current rules) and ref-structs (opposite: current rules are insufficient to detect type-safety violations).
However, we need to start with something, so let’s start with ref returns. 
Immediately actionable pieces:
-	Who should be on board when we take decision on this?
-	Do we …

Extension of IL verification rules to address ref returns

---

proposed/verifiable-ref-readonly.md

A proposal for extension of IL verification rules that would allow operating with readonly references without defensive copying in verifiable code.
In the nutshell the rules would allow type-safe scenarios like fetching a reference to a readonly field and passing that to an “in” parameter be formally verifiable. 
The proposal explains how “readonliness” demands and guarantees can be propagated and validated by the IL verification algorithm.

Extension of IL verification rules to address readonly references

---

accepted/build/standard-ci-env-variables.md

This is the name of the SCM the repo is using.
Although there might be better names than `STANDARD_CI_REPOSITORY_TYPE` (like `STANDARD_CI_SCM`) I chose it for pragmatic reasons - the term "repository type" is already used by NuGet in nuspec metadata. We don't strictly need to be consistent but for the sake of less complexity it's better to be.

Adds STANDARD_CI_REPOSITORY_TYPE

---

proposals/sdk-version-scheme.md

Builds of the .NET Core SDK will soon reflect this scheme described in this document.

Add plan for .NET Core SDK version numbers

---

accepted/runtime-binding.md

Describe interaction with `applyPatches`.
`version` is always requires as it acts as the lower bound (needed even for `LatestMajor`).
Be specific about automatic patch roll forward.
Fix typos and some formatting.

Small fixes to the runtime binding design

---

accepted/single-file/design.md
accepted/single-file/extract.md
accepted/single-file/staging.md

The is a design proposal for supporting single file distribution in .Net Core.
To run apps published as a single-file, [CoreCLR#20287](https://github.com/dotnet/coreclr/issues/20287) proposed extracting out all the embedded dependencies to files at startup.
However, based on customer feedback through public and private fourms, the current design uses a hybrid of in-memory execution and extraction to files.
Further stages of improvements are outlined in `staging.md`.

Publishing to Single-file in .Net Core

---

accepted/single-file/design.md

Fix a copy-setting in a sample for excluding certain
files in the publish directory from the single-file

Fix a setting wrt excluding files.

---

accepted/diagnostics/source-link.md

Fixed a small typo error in VSTS Git URL from .../_api/... to .../_apis/...

Correct URL for VSTS Git example

---

accepted/single-file/design.md
accepted/single-file/direct.md

This change adds certain details about accessing the files
embedded within  asingle-file bundle without having to spill
them to files on disk.

Single-file: Add notes about accessing files from Bundle

---

accepted/single-file/extract.md

This commit changes the way the location where files in a bundle
are extracted can be influenced at build time.
Originally, they were written as properties in `runtimeconfig.json` file,
which is complex to handle at runtime, because the apphost needs to
extract resources before `hostfxr` process `runtimeconfig.json`
(because hostfxr itself needs to be extracted).
Instead the configurations are now build-time properties, which can be
written to and processed from the bundle-headers.

Single-File: Extraction configurations as build-time properties.

---

accepted/install-locations.md

Description of various supported installation types (and locations) for .NET Core 3.0 runtime and SDK. Proposals for 3.0 behavior to create consistency between platforms.
Important for 3.0 as we're shipping new hosts which don't have a servicing solution.

.NET Core installation types for 3.0

---

accepted/targeting-packs/targeting-packs.md

We believe this is the final plan. Modulo more feedback, we'll be accepting this.
/cc @dsplaisted @marek-safar

Easy Acquisition of .NET Framework Targeting Pack

---

accepted/single-file/staging.md

By using memfd_create(), it's possible to create a ephemeral file that's mapped by the same kind of backing store that a mmap() with MAP_ANONYMOUS would have.  It's possible to obtain a file path for this file in /proc and then feed it to dlopen().

Propose method to dlopen() from memory

---

accepted/2020/better-obsoletion/better-obsoletion.md

@RikkiGibson [said this](https://github.com/dotnet/roslyn/issues/42119#issuecomment-599753623):
> A key bit of the spec, and how we are landing on it in terms of behavior:
> 
> > The compiler should assume that UrlFormat and DiagnosticId are independent features, in other words both can be used, either, or neither.
> 
> The expected behaviors for "neither", "both", or "only DiagnosticId provided" are fairly straightforward. But I wanted to be clear about the case where UrlFormat is provided but DiagnosticId is not provided: **we will use the DiagnosticId that the compiler chooses by default as the format argument to UrlFormat**. This could be `CS0618`, `CS0619`, `CS1062`, or `CS1063`. The internal error codes don't consider leading zeroes, but the padding is important when we actually do …

Clarify behavior for Better Obsoletion

---

accepted/2020/workloads/workload-resolvers.md

This spec covers some of the implementation for optional SDK workloads in .NET 5.  The overall spec is in #100.

Add spec for workload resolution in MSBuild

---

accepted/2020/minimum-os-version/minimum-os-version.md
accepted/2020/workloads/workloads.md

This spec describes a standard mechanism for libraries to express the availability of APIs on different platforms and different versions of those platforms using attributes and MSBuild properties, and how those annotations can be used to improve the developer experience at multiple levels. It's based on the model already present in Xamarin.iOS.
I expect parts to be split into other documents and refined but this should be a good starting point.

Add spec for MinimumOSVersion.

---

accepted/2020/net5/net5.md

Sorry, I didn't notice this didn't get changed after our last conversation. My understanding was that this was going to be how we handled -all- relevant files. I'm a bit hesitant about making the change as currently specified (I've already done this over at https://github.com/NuGet/NuGet.Client/pull/3339), but I notice we have some failing tests due to that. /cc @nkolev92 @rrelyea 
Anyway, this PR isn't a hard requirement, but a preference, if you think it's fine to do this for consistency and safety's sake, @terrajobst

use friendly name for project.assets.json

---

accepted/2020/minimum-os-version/minimum-os-version.md

* Makes it so that element names do not contain periods or dashes, which could cause issues in some scenarios e.g. deserialization.
* Make it clearer that the platformInfo metadata is applied to reference assemblies based on their target framework
Fixes #121 - NuGet Manifest XML format

Improve platformInfo NuGet metadata

---

accepted/2020/platform-checks/platform-checks.md

This provides the attribute and analyzer needed to realize #97.

Add analyzer for platform-specific APIs

---

accepted/2020/better-obsoletion/binaryformatter-obsoletion.md

This document covers the winding down of `BinaryFormatter` within .NET.
Starting with .NET 5, we'll start obsoleting APIs and disabling `BinaryFormatter`-related features in certain project types. Eventually all code within the dotnet repo is to be migrated fully off of `BinaryFormatter`, at which point the implementation is to be removed from the runtime.
/cc @terrajobst

BinaryFormatter long-term obsoletion plan

---

accepted/2020/windows-specific-apis/windows-specific-apis.md

I made a mistake when I ran this tool last time -- I didn't clean my build. The result is that the previous state was based on .NET Core 3.1. This brings it forward to .NET 5 Preview 6.

Add additional Windows-specific APIs

---

proposed/SerializerGoals5.0.md

Based on a prior internal review and feedback, putting various information together to discuss.

JSON Serializer recommendations for 5.0

---

accepted/2020/single-file/design.md

https://github.com/dotnet/sdk/pull/12724 changed the option names.
https://github.com/dotnet/runtime/pull/41809 is changing the Linux ARM64 bundling behavior.

Update single file docs

---

meta/template.md

I also noticed the link to the ASP.NET Designs repo in the readme (https://github.com/aspnet/specs) is dead, but I'm not sure where  it was moved to. (Or maybe it's just private?)

Fixed example links in proposal template

---

README.md

As requested in https://github.com/dotnet/designs/pull/166#issuecomment-733954027
Part of me wonders if maybe we should just mark it as internal, but I suppose anyone who needs to know about that repo already does.

Removed internal-only link to the ASP.NET specs repo

---

accepted/2020/linking-libraries.md

This change updates the document to:
* Match the behavior as implemented in .NET 5
* Describe the goals and how we plan to achieve them as of .NET 6 beginning
* Provide a more detailed description of the various techniques used to solve trim warnings
* Make the description more generic to apply to all libraries, not just the core framework
* Include description of wider user experiences
* Add links to issues and proposals as of .NET 6 planning

Update the "linking libraries" document to match current plans

---

accepted/2020/reproducible-builds.md

This spec covers the reproducible builds the .NET, NuGet, and Terrapin teams have been working on.

Add reproducible build spec

---

proposed/flexible-http.md

This is a proposal for a flexible, high-performance HTTP API. In shorthand, this may be referred to as "LLHTTP".
A prototype working towards this is at: https://github.com/scalablecory/NetworkToolkit/

Flexible HTTP API

---

accepted/2020/platform-exclusion/platform-exclusion.md

According to our [conceptual documentation](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer) we should use Build not Version, eg. `windows10.0.18362` instead of `windows10.0.1903`, otherwise it would be inconsistent with TFM-s and capability checking API-s. Also note that Windows 10 versions are switching to new a scheme (`20H2`, `21H1` ...), which will make it impossible to use them with the attribute.
Despite the 3 reviewers (!), I almost made a mistake in dotnet/runtime#45494, which is probably the first PR in our libs using a specific version with `SupportedOSPlatformAttribute`. It was @filipnavara who spotted the mistake.
@buyaa-n @jeffhandley @terrajobst please confirm if this is correct, I need to be 100% sure before merging that PR.

platform-exclusion.md: platform attributes should use Build not Version with Win10

---

accepted/2020/workloads/workload-manifest.md

Add spec for workload manifests, expanding on the concepts from the [workload overview](https://github.com/dotnet/designs/blob/master/accepted/2020/workloads/workloads.md).

Add spec for workload manifests

---

accepted/2021/statics-in-interfaces/README.md
accepted/2021/statics-in-interfaces/designs/README.md
accepted/2021/statics-in-interfaces/requirements/README.md
accepted/2021/statics-in-interfaces/scenarios/README.md

CC. @terrajobst, @MadsTorgersen 
This is the skeleton (following the same template as for utf8) for the statics-in-interfaces/generic-math design for the libraries.

Adding the skeleton for statics-in-interfaces

---

.github/workflows/index.yml
INDEX.md
README.md
accepted/2020/diagnostics/activity-improvements.md
accepted/2020/workloads/workload-manifest.md
accepted/2020/workloads/workload-resolvers.md
accepted/2020/workloads/workloads.md

- CI action to cause a failure if the index is out of date.
Fix some anomalies in the activity-improvements design that already
crept in and were causing CI failures.
- Updated steps in the README to add a note about updating the index.
Thanks for the suggestion, @akoeplinger 
- Fix some leftover FIXME notes in designs.
I used the file history to guess who the owners were. I decided *not*
to add commit co-authors to the design index, since those commits read
like code review rather than designer authorship.
This does not address these two comments:
@danmoseley said:
> do you feel like a follow up change that merges Dev/PM into Owners? If not LMK and I can do it.
I am going to work on this next, but as a separate PR: #194 
@jeffhandley  said:
> @terrajobst Since we recently started adding …

Followup from adding a design index

---

INDEX.md
accepted/2021/statics-in-interfaces/README.md
accepted/2021/statics-in-interfaces/designs/README.md
accepted/2021/statics-in-interfaces/requirements/README.md
accepted/2021/statics-in-interfaces/scenarios/README.md
tools/update-index/Program.cs

Since we're starting to move away from the `proposed` folder and instead mark designs as **DRAFT**, this PR recognizes the `**DRAFT**` marker in design documents and introduces a "Drafts" section to the index. This change also:
* Allows either `"**Owner**"` or `"**Owners**"` to be recognized
* Recognizes comma-separated lists of owners (in addition to pipe-separated lists)
* Limits recognition of Title, Owner, and Draft to content above the first subheading (avoiding false positive matches within document contents)
* Flattens the structure of the statics-in-interfaces draft per feedback on #186 (FYI @tannergooding)

Recognize draft design documents

---

INDEX.md
accepted/2021/flexible-http.md

We're starting to move away from the `proposed` folder; once proposed designs are accepted, all links to the design become broken. Instead, we can now mark design docs as drafts and they are included in the index as such. This PR moves the Flexible HTTP APIs document into the `accepted` folder and marks it as a draft.

Mark Flexible HTTP as a Draft within the Accepted folder

---

accepted/2020/serializer/WriteableDomAndDynamic.md

High-level design and initial API thoughts to review before submitting the formal API issue.
Links to feature request https://github.com/dotnet/runtime/issues/29690

Writable DOM and dynamic support for 6.0

---

accepted/2020/net5/net5.md

The documentation file that I looked at was incorrect at this and when I tried to do the comparison at the bottom I noticed there was errors with it and then looked internally in the SDK and found out it actually prefixes it with an ``v`` and the one I needed was the one without the ``v`` prefix.
As such I felt this document needed some changes and also to note for future viewers what to use if they do not want the prefix from TFV.

Specify that TFV includes the 'v' prefix on it's value, and also fix comparisons to use msbuild functions instead.

---

INDEX.md
accepted/2021/nano-framework-tfm/nano-framework-tfm.md

TFM for .NET nanoFramework

---

accepted/2021/net6.0-tfms/net6.0-tfms.md

Context: https://github.com/NuGet/NuGet.Client/pull/4011#issuecomment-825898873
The `Compatibility rules` section in `net6.0-tfms.md` didn't list the
precedence rules for `net6.0-android`.
These should be the same as `net6.0-ios`, except that instead of
`xamarin.ios`, we have:
* `monoandroid1.0`
* `monoandroid4.4`
* `monoandroid4.4.87`
* `monoandroid5.0`
* `monoandroid5.1`
* `monoandroid6.0`
* `monoandroid7.0`
* `monoandroid7.1`
* `monoandroid8.0`
* `monoandroid8.1`
* `monoandroid9.0`
* `monoandroid10.0`
* `monoandroid11.0`
* `monoandroid12.0`
This can be illustrated somewhat by the `$(PackageTargetFallback)`
workaround the Android workload is using in the current .NET 6
previews:
https://github.com/xamarin/xamarin-android/blob/e59f6493fedd789cbd3157d369104516cfffd3f0/src/Xamarin.Android.B …

Include net6.0-android in precendence rules

---

accepted/2021/net6.0-tfms/net6.0-tfms.md

Context: https://github.com/NuGet/NuGet.Client/pull/4011#issuecomment-829301719
There is no mention of `net6.0-tizen` in the `Compatibility rules` section.
These should be the same as `net6.0-ios` except that `tizen` is used instead of `xamarin.ios`.
And the Tizen platform runtime identifiers should also be added to the `RIDs` section.
Tizen is preparing to provide `net6.0-tizen` TargetFramework in https://github.com/Samsung/Tizen.NET  to support .NET6 and MAUI.

Include tizen6.0-tizen in precedence rules

---

accepted/2021/install-location-per-architecture.md

This is a proposal how to update the install location behavior in .NET 6 to support multiple architectures on a single machine across all platforms.

Support multi-arch install locations

---

accepted/2021/System.Diagnostics/Metrics-Design.md

https://github.com/dotnet/runtime/issues/44445

Metrics Design

---

accepted/2020/minimum-os-version/minimum-os-version.md

Update the Minimum OS Version spec to align with the later designs in the Platform Checks speck.

Align minimum-os-version with platform-checks

---

accepted/2020/workloads/workload-manifest.md

Expand explanation of extending workloads and clarify how platform restrictions interact with it.

Clarify workload extension & platform restrictions

---

accepted/2021/blazor-wasm-crypto.md

This document discusses how we intend to support cryptographic scenarios in Blazor/wasm apps in .NET 6 and beyond. It intends to address the common use case of developers wanting access to HMACSHA\* and AES in Blazor/wasm apps.

Proposal for Blazor/wasm crypto support in .NET 6 and beyond

---

accepted/2021/winforms/streamline-application-bootstrap.md

We had further internal discussions and it was concluded that we're not ready for HightDpi.PerMonitorV2 to be set as a default as this stage. Updating the default value to "system aware".
Relates to https://github.com/dotnet/winforms/pull/5392

Update the default dpi value

---

accepted/2021/x64-emulation-on-arm64/x64-emulation.md

We're working on a plan to support .NET for x64 emulation on Arm64, on macOS and Windows. There are multiple decision points that we are needing to navigate to make a decision. This document is intended to explore those.

Add plan for x64 emulation

---

accepted/2020/diagnostics/source-link.md

Trailing characters make the copyable URL invalid. This makes the copy-button inconvenient to use, since the copied URL must be manually edited afterwards.

Remove trailing characters from copyable URL

---

accepted/2021/signed-package-verification/re-enable-signed-package-verification.md

NuGet package signing is a critical component of determining trustworthiness and establishing a secure supply chain. We enabled package signing verification with .NET 5 but had to disable it shortly after enabling it. Fundamentally, this unfortunate need to disable a critical security feature occurred due to not fully understanding the certificate authority landscape and being biased to Windows operating system capabilities. This proposal resolves the challenges we discovered in large part by leveraging Windows capabilities in a new cross-platform model. We do not see any additional headwinds to durably re-enabling signed package verification.
Technical details: [Proposal to re-enable cross-platform signed NuGet package verification (technical …

Proposal to re-enable signed NuGet package verification

---

accepted/2021/signed-package-verification/re-enable-signed-package-verification-technical.md

This document details the technical solution for the proposal to [re-enable cross-platform signed NuGet package verification](https://github.com/dotnet/designs/pull/245).
CC @richlander, @omajid

Proposal to re-enable cross-platform signed NuGet package verification (technical details)

---

accepted/2021/install-location-per-architecture.md

Change the way multi-arch configuration files are written. Use one file per architecture (instead of one file with multiple lines in it). This makes it much simpler for installers to read and write these configuration files. It also somewhat simplified the product as it doesn't need as complex parsing logic.
Minor cleanup in other areas of the doc.

Change the configuration to use file per arch

---

accepted/2021/logging-generator.md

typo fix
btw this design doc doesn't mention about `SkipEnabledCheck`

Fix typo in logging-generator.md

---

.editorconfig
accepted/2021/statics-in-interfaces/README.md

**IMPORTANT:** This is very much a draft of the API surface and there are several open questions and design points still to be resolved.
The current UML diagram looks something like:
There are four related language proposals for this feature:
* https://github.com/dotnet/csharplang/issues/4436 - Static abstract members in interfaces
* https://github.com/dotnet/csharplang/issues/4665 - Checked operators
* https://github.com/dotnet/csharplang/issues/4666 - Relaxing shift operator requirements
* https://github.com/dotnet/csharplang/issues/4682 - Unsigned right shift operator
There are also runtime related changes for this feature:
* https://github.com/dotnet/runtime/pull/49558

Adding a rough draft of the "minimum viable product" for the .NET Libraries APIs to support generic math

---

accepted/2021/statics-in-interfaces/README.md

As per https://github.com/dotnet/runtime/issues/67744, we decided that the non-numeric types, such as `DateOnly`, `DateTime`, `DateTimeOffset`, `Guid`, `TimeOnly`, and `TimeSpan` would not implement the numeric related interfaces (those in they `System.Numerics` namespace). Instead they would only implement the core interfaces from the `System` namespace (such as `IComparable`, `IEquatable`, `IFormattable`, and `IParsable`).

Updating the statics-in-interfaces design doc to match the last design review decision

---

INDEX.md
accepted/2019/support-for-memory-limits.md

I made a few changes:
- Add `--cpus` context.
- Add `DOTNET_PROCESSOR_COUNT` context.
- Fix my broken math!
@Maoni0 @jkotas

Add --cpus context

---

accepted/2021/preview-features/preview-features.md

This adds a clarification that specifically calls out that preview features are only support for an SDK's current framework version.

Clarify preview behavior for SDKs

---

accepted/2022/FunctionPointers.md

Design that should be approved before implementation is continued and before we update API issues.

Function pointer design

---

INDEX.md
accepted/2023/preview-apis/preview-apis.md

In .NET 6, we've added a way to [ship preview features](https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md) in otherwise stable releases. It works by tagging APIs (and language features) as preview features and requiring the user's project to explicitly opt-into using them via the `<EnablePreviewFeatures>` property.
The feature was primarily designed to accommodate platform-level features, that is for features that span runtime, library, and language, such as generic math. However, we also believed that the feature would work for libraries that want to offer preview functionality in otherwise stable NuGet packages.
Since then, we've seen requests from partners who have tried using it and hit limitations that come from guardrails we put into …

Experimental APIs

---

proposed/vector-instruction-set-default.md

- .NET defaults to SSE2 instructions.
- We should default to a newer instruction-set, for higher performance.

Proposal for vector instruction default

---

accepted/2023/preview-apis/preview-apis.md

Clarify behavior of severity

---

INDEX.md
proposed/sdk-analysis-level.md

This is the first pass at SdkAnalysisLevel, a unified flag to help users manage their SDK warning levels in situations where they may not be able to pin SDKs via global.json or other means.  The property is intended to communicate to tooling like the compilers an explicit intent - "treat me as if I were SDK X.Y.Z" without requiring the user to install or manage other SDKs. The first well-defined use of this is the Roslyn field member breaking change, where members of the Roslyn team hope to use this flag in conjunction with other user signals to determine if a user should get warnings about the field breaking change.
I've spoken with most of the folks mentioned in the stakeholders/reviewers section about this before - now it's time to get broader input and push the design to done.

Add a design for SdkAnalysisLevel

---

INDEX.md
accepted/2024/net-standard-recommendation.md

We'd like to issue a warning when building a project targeting .NET Standard 1.x and recommend the user to upgrade to .NET Standard 2.0.
The reason being that some developers still target .NET Standard 1.x even though it doesn't buy them any additional reach as all in supported flavors of .NET all support .NET Standard 2.0 or later.
The goal of this warning is allow people to set their projects more up for success; that is, have good reach while also being able to have a sizeable feature set (both in terms of framework APIs as well as NuGet packages they can reference).
Please note that this will not issue a warning for .NET Standard 2.0/2.1, nor are we changing anything around versions of .NET Standard can be built or referenced.

Add design document for issuing a warning when targeting netstandard1.x

---

tools/update-index/update-index.csproj

Since ubuntu has floated to .NET 8 and the tool doesn't have roll-forward configured pipelines are failing.
Example failing job run:
https://github.com/dotnet/designs/actions/runs/13055636223/job/36425868529

make the indexer tool run on the default ubuntu instance

---

accepted/2025/memory-safety/memory-safety.md

[Rendered markdown](https://github.com/dotnet/designs/blob/memory-safety/accepted/2025/memory-safety/memory-safety.md)
We plan to make memory safety a focus for the next couple releases. This document describes the overall plan and motivation. It references https://github.com/dotnet/designs/pull/330, which is an important part of the plan. Memory safety has always been a critical design tenet of C# and .NET. Now is a good time to revisit memory safety design assumptions and product behaviors. We believe we have an opportunity to significantly improve security posture for all .NET developers with this project.
Our plan is significant, however, it is not a breaking change. We plan to make the proposed behaviors opt-in for existing code. Like nullable, new templates may opt users into the …

Memory safety plan
