dotnet/designs

README.md

Added missing links to F# design/suggestions repo's

Add links to F# design docs

---

README.md
accepted/platform-intrinsics.md

Adds the high level design for platform dependent intrinsics
and specifies a process for adding them.  The commit also
adjusts the README to reflect new folders to allow PRs to designs.

Add platform dependent intrinsic process/design

---

proposed/standard-ci-env-variables.md

Add environment variables for AWS CodeBuild

Add AWS CodeBuild to standard-ci environment variables

---

meta/proposals.md
meta/template.md

This adds a write-up of why proposals are important as well as a template with guidance on how to write them.

Add meta information about proposals

---

accepted/cross-platform-performance-monitoring.md

This document covers a proposed design for consuming performance and tracing data and exposing it to performance monitoring systems.

Cross Platform Performance Monitoring

---

accepted/automatic-redirects-by-default/automatic-redirects-by-default.md

This document describes the changes necessary for turning on automatic binding redirect generation by default.

Add initial draft of "Automatic Binding Redirection By Default"

---

accepted/performance-profiling-controller.md

Design for out-of-proc exposure of EventPipe profiling and tracing functionality.

Add Performance Profiling Controller Design

---

accepted/single-file/design.md

Add LibZ to related work section of single-file design doc.

SingleFile: Add related work

---

accepted/single-file/extract.md

Fixed typo regarding final app-root location

---

accepted/single-file/design.md

Fix the use of --single-file boolean switch

Single-File: Fix a typo in the usage section

---

accepted/2020/single-file/design.md

Update single file publish link

---

accepted/2020/net5/net5.md

We need to decide what precedences we want the new TFMs to have in relation to the old ones. For example, consider this scenario:
* Project: `net5.0-ios`
* Package:
* `net5.0`
* `xamarin.ios`
Both `net5.0` and `xamarin.ios` are applicable for the project. Which assets should NuGet prefer?

Clarify precedences of TFMs

---

proposed/activity-improvements.md

There was a missing bracket `)` in the code sample

Fix a missing bracket in the code sample

---

accepted/2020/linking-libraries.md

Plan for making the .NET Libraries linker-friendly.
cc @vitek-karas @stephentoub @jkotas @marek-safar

Linking the .NET Libraries

---

accepted/2020/cbor/cbor.md

Relevant implementation changes https://github.com/dotnet/runtime/pull/37956

Update CBOR design to include API review feedback

---

accepted/2020/better-obsoletion/obsoletions-in-net5.md

This captures a few changes identified during the implementation of https://github.com/dotnet/runtime/pull/39269.

Update obsoletions spec to match implementation

---

accepted/2020/windows-specific-apis/windows-specific-apis.md

while working on https://github.com/dotnet/runtime/pull/40610 I've found some minor issues
@terrajobst @jeffhandley PTAL

update Windows-specific API list

---

accepted/2020/windows-specific-apis/windows-specific-apis.md

Correcting the attribute type name.  Removing a couple of open items that have since been closed.

Update windows-specific API doc to reflect updates

---

accepted/2019/targeting-packs-and-runtime-packs.md

Changed word "targeting" to "runtime".

---

INDEX.md
accepted/2021/platform-dependencies/platform-dependencies.md

CI is broken due to a missing entry.  cc @omajid @maryamariyan

Make sure Index.md is up to date

---

.github/workflows/index.yml
INDEX.md
README.md
update-index

cc @omajid 
I was able to get this working on Windows using python3 with some small fixes.

Make update-index work on Windows

---

accepted/2020/workloads/workload-manifest.md

Make workload aliasing behavior explicit and enable the behavior needed by https://github.com/dotnet/aspnetcore/pull/31761. Workload reader PR to follow.

Clarify workload pack aliasing behavior

---

accepted/2021/logging-generator.md

Fixes a broken link in `accepted/2021/logging-generator.md`

Broken link

---

accepted/2021/preview-features/preview-features.md

In an earlier design I proposed that the analyzer handles use of preview APIs while the compiler handles use of language features that depend on preview runtime features. This proposal shifts the enforcement entirely to the analyzer.

Remove compiler enforcement and let the analyzer handle it

---

accepted/2021/objectivec-interop.md

See https://github.com/dotnet/diagnostics/pull/2407 for SOS update.
/cc @noahfalk @hoyosjs @jkoritzinsky @elinor-fung @rolfbjarne

Update design based on SOS implementation.

---

accepted/2020/workloads/workload-manifest.md
accepted/2021/workloads/workload-installation.md

Add spec for .NET SDK workload installation.
Still to come: Details on how .NET SDK workload installer interacts with Visual Studio installer.

Add workload installation spec

---

accepted/2020/better-obsoletion/binaryformatter-obsoletion.md

As approved by Tactics yesterday.

Update BinaryFormatter obsoletion strategy doc

---

tools/update-index/update-index.csproj

It causes CI failures on Pull Requests.

Update the `update-index` tool to .NET 6.

---

INDEX.md
accepted/2023/net8.0-browser-tfm.md

Adds a proposal for creating a browser specific TFM.
[Rendered](https://github.com/dotnet/designs/blob/40b628e100a8b82bdc92dcdf210a8743e30128c0/accepted/2023/net8.0-browser-tfm.md)

net8.0-browser TFM

---

INDEX.md
accepted/2025/memory-safety/memory-safety.md

Updated link for C# unsafe annotation and compiler feedback.
@agocke

Update link for unsafe proposal
